### ISSUE TITLE
[Bug]: Missing Sensors

### ISSUE THREAD

**Issue by Chris-777** [rainepretorius/olarm-ha-integration#121]
### Contact Details

cdednam+github@gmail.com

### What happened?

I've been using this integration for a while now with my EVO192 and had a persistent issue where only the 1st 37 zones binary sensors are created. However the bypass switches for all 64 zones are created. Any ideas?

### Version

2.3.1

### Downloaded integration debug logs.

```shell
This error originated from a custom integration.

Logger: olarm_api_rainepretorius
Source: custom_components/olarm_sensors/coordinator.py:132
integration: Olarm Sensors (documentation, issues)
First occurred: 15:22:04 (129 occurrences)
Last logged: 16:05:14

Olarm sensors error for device (The Farm): list index out of range
```

**Comment by rainepretorius** [comment]
I will have to check to see. I no longer have an Olarm to test with.. I replaced it with an esp32 and Paradox Alarm Interface.

**Comment by witc-git** [comment]
> I will have to check to see. I no longer have an Olarm to test with.. I replaced it with an esp32 and Paradox Alarm Interface.

Would you mind doing a write-up of your setup for others who are tired of waiting for Olarm? Do you think it will work with both the ESP and Olarm simultaneously? (Security company uses Olarm to monitor)

**Comment by drzoidberg33** [comment]
> I replaced it with an esp32 and Paradox Alarm Interface.



> > I will have to check to see. I no longer have an Olarm to test with.. I replaced it with an esp32 and Paradox Alarm Interface.
> 
> Would you mind doing a write-up of your setup for others who are tired of waiting for Olarm? Do you think it will work with both the ESP and Olarm simultaneously? (Security company uses Olarm to monitor)

I too moved away from this integration a while ago (the Olarm API sucks for realtime use).

I'm also using an ESP32-based solution using PAI. I'm using the Serial over IP connection option: https://github.com/ParadoxAlarmInterface/pai/wiki/Connection-methods

I wanted to keep my Olarm hardware but couldn't get both the ESP32 and the Olarm to work reliably over a single serial connection on my original MG5050 panel, so I upgraded mine to the MG5050+ which has two serial pinouts. Now I still have a working Olarm (which I might decommission as some point) and the ESP32 on the same panel and it's been very reliable.

@witc-git the link I provided for API should have all the info you need but if you have any questions feel free to ask.
