### ISSUE TITLE
Version 2.0.0: KeyError: 'olarm_arm_code'

### ISSUE THREAD

**Issue by drzoidberg33** [rainepretorius/olarm-ha-integration#29]
Just updated to 2.0.0 and it fails to start up.

```
Logger: homeassistant.config_entries
Source: custom_components/olarm_sensors/__init__.py:43
Integration: Olarm Sensors ([documentation](https://github.com/rainepretorius/olarm-ha-integration/blob/main/README.md), [issues](https://github.com/rainepretorius/olarm-ha-integration/issues))
First occurred: 09:10:23 (1 occurrences)
Last logged: 09:10:23

Error setting up entry Olarm Sensors for olarm_sensors
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/olarm_sensors/__init__.py", line 43, in async_setup_entry
    not config_entry.options[CONF_ALARM_CODE]
KeyError: 'olarm_arm_code'
```

**Comment by rainepretorius** [comment]
Hi, 
It is because you updated from a verdion earlier than 1.1.8 to 2.0.0. Please redo the setup as in the release details of Version 1.1.8 to fix the invallid config entry.

**Comment by drzoidberg33** [comment]
Hmm, this is with a completely clean install of 2.0.0 after removing and re-installing the integration.

Let me double check again.

**Comment by drzoidberg33** [comment]
Yep, even after removing the custom repository and re-installing and restarting HA between each step, I still get this error - whether set a code or not.

<img width="325" alt="image" src="https://user-images.githubusercontent.com/1313205/230572762-8c7e16a7-4493-452a-965d-a2cea907e7cd.png">
