### ISSUE TITLE
Alarm Panel Entity: This entity is no longer being provided by the olarm_sensors integration after restart of HA

### ISSUE THREAD

**Issue by jakesie1309** [rainepretorius/olarm-ha-integration#40]
Hi there

I have notice that every time i restart HA, the alarm panel entity does not work. The only way to fix this is to remove the integration, re-setup and then the alarm panel works again.

Logger: homeassistant.config_entries
Source: helpers/entity_component.py:169
First occurred: 09:01:35 (3 occurrences)
Last logged: 09:01:35

Error setting up entry Olarm Sensors for alarm_control_panel
Error setting up entry Olarm Sensors for binary_sensor
Error setting up entry Olarm Sensors for button
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/alarm_control_panel/__init__.py", line 115, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 169, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!

**Comment by rainepretorius** [comment]
Hi,
What alarm panel do you use? Is it also possible to send the response of this request (https://apiv4.olarm.co/api/v4/devices/<your_device_id>?accessToken=<your_api_key>)

**Comment by jakesie1309** [comment]
Hi,
It is a paradox MG5050.
Will send request once back at home

**Comment by jakesie1309** [comment]
Hi, are you looking for any info in the api output. there are some sensitive information that i don't really want to share on the internet.

PS, API call looks normal and see all info just fine

**Comment by rainepretorius** [comment]
I cannot seem to find an issue in the code that would reproduce this error for me. I updated the code to improve logging when the integration is set to debug mode. This will allow me to see where the issues might occur.
