### ISSUE TITLE
JSON decode error

### ISSUE THREAD

**Issue by EmileSpecs** [rainepretorius/olarm-ha-integration#48]
As of 2.1.x I get this error.

The integration is not functional at all.
Seems like all data fetched isn't decoded.

Not sure if it's the request of response mimetype that's wrong, either way, should be an easy enough fix.

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/olarm_sensors/olarm_api.py:497
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 6:34:32 AM (1 occurrences)
Last logged: 6:34:32 AM

[547636758368] 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://apiv4.olarm.co/api/v4/devices')

**Comment by rainepretorius** [comment]
Please refer to this issue. Update to Version 2.1.1. Then restart and enter your new api key under the Configure button. Your API key has been blocked by Olarm.

**Comment by EmileSpecs** [comment]
The error above was after upgrading to 2.1.1 and also I've reset / regenerated my API key more than once.

I suspect the only long term solution here is to use webhooks. Do you have any plans yet to implement a webhook solution, this will also make the service much more responsive I would imagine.
