### ISSUE TITLE
Entities become unavailable after a few days 

### ISSUE THREAD

**Issue by tophermetcalfe** [rainepretorius/olarm-ha-integration#56]
I have been able to set up the integration with the sensors and entities working for a while, then randomly the entities become unavailable. The only way I have been able to fix this is to remove the integration and setup again with the same API key. Then it works but after a few days, it becomes unavailable again. Am I doing something wrong? Thanks so much for your help.

**Comment by rainepretorius** [comment]
Please check issue:
https://github.com/rainepretorius/olarm-ha-integration/issues/49
