### ISSUE TITLE
NotFound http error when calling Olarm API device /actions endpoint

### ISSUE THREAD

**Issue by jonathankretzmer** [rainepretorius/olarm-ha-integration#7]
Hi there,

I had a few issues installing this custom HA HACS plugin, it seemed to be crashing.

I narrowed it down to the Olarm API when it called /actions for the device. When emulating the API call in Postman, with the API key as the bearer auth header, it was coming back with an HTTP 404 error, "Not found". So this is obviously what was causing the errors.

When I commented out the calls to `api.get_changed_by_json()` then I managed to get it all working.

I'm not up to speed on whether there are possibly multiple different versions of the Olarm devices and/or APIs available?

**Comment by rainepretorius** [comment]
Hi Jonathan,

Please note that this error has been generated by Olarm and means that your device could not be found. Please ensure that your deviceid is correct.

**Comment by jonathankretzmer** [comment]
This API call works:
https://apiv4.olarm.co/api/v4/devices/8edcd590-a19b-42d3-b6b3-<snipped>?accessToken=<snipped>

This API call fails with 404 NotFound:
https://apiv4.olarm.co/api/v4/devices/8edcd590-a19b-42d3-b6b3-<snipped>**/actions**?accessToken=<snipped>

I received the device_id by following the steps in the README, using the call:
https://apiv4.olarm.co/api/v4/devices?accessToken=<snipped>

**Comment by rainepretorius** [comment]
I will also have a chat with them this week to see if it is maybe a unsupported feature for your device. Can you please let me know what Model of Olarm you are using and your alarm system Manufacturer.

**Comment by NeilDuToit92** [comment]
It seems like the API only returns actions that happened in the last few days.
So if you didn't arm or disarm the alarm in a few days, the endpoint returns a 404.
