### ISSUE TITLE
[Bug]: Index out of range

### ISSUE THREAD

**Issue by JacquesDuToit** [rainepretorius/olarm-ha-integration#70]
### Contact Details

jacques@itdecs.co.za

### What happened?

i keep getting this after install i cant seem to get it to work is it something im doing wrong?

### Version

2.2.2

### Relevant log output

```shell
IndexError: list index out of range
2023-08-07 07:14:42.740 DEBUG (MainThread) [custom_components.olarm_sensors] Finished fetching Olarm Coordinator (19 plataan) data in 0.479 seconds (success: False)
2023-08-07 07:14:52.489 ERROR (MainThread) [custom_components.olarm_sensors] Unexpected error fetching Olarm Coordinator (19 plataan) data: list index out of range
Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/olarm_sensors/coordinator.py", line 142, in _async_update_data
    return await self.update_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/olarm_sensors/coordinator.py", line 110, in update_data
    self.panel_data = await self.api.get_panel_states(self.devices_json)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/olarm_sensors/olarm_api.py", line 299, in get_panel_states
    if olarm_zones[area_num] == "":
       ~~~~~~~~~~~^^^^^^^^^^
```

**Comment by JacquesDuToit** [comment]
Sorry i have a paradox sp65

**Comment by rainepretorius** [comment]
> Sorry i have a paradox sp65

Hi @JacquesDuToit ,

I will look into this error asap. This os the first error in a while that I have gotten. I will check what could cause it and make the relevant changes to resolve this issue.

**Comment by JacquesDuToit** [comment]
Hi did u manage to check the error is it something im doing wrong?

**Comment by rainepretorius** [comment]
I checked through the code and the error and could not replicate it. How is your Olarm Set up? How many areas do you have on your panel and how many zones are set up on Olarm here: Devices -> Setup -> Areas?

**Comment by JacquesDuToit** [comment]
2 areas 17 zonesSent from my Galaxy
-------- Original message --------From: Raine Pretorius ***@***.***> Date: 2023/08/23  08:39  (GMT+02:00) To: rainepretorius/olarm-ha-integration ***@***.***> Cc: JacquesDuToit ***@***.***>, Mention ***@***.***> Subject: Re: [rainepretorius/olarm-ha-integration] [Bug]: Index out of range (Issue #70) 
I checked through the code and the error and could not replicate it. How is your Olarm Set up? How many areas do you have on your panel and how many zones are set up on Olarm here: Devices -> Setup -> Areas?

**Comment by rainepretorius** [comment]
Ok. 
And the setup on the app?

**Comment by JacquesDuToit** [comment]
I Don’t Konow what im doing wrong so I go to settings add integration add olarm sensonrs put in api code and then it gives me 1 device and 1 entity. Entity says button19_ Refresh when I refresh it gives an error

**Comment by JacquesDuToit** [comment]
Here is the whole file I get

**Comment by rainepretorius** [comment]
Hi @JacquesDuToit ,
I do not see the file. Can you maybe email it to me at raine.pretorius1@gmail.com ?

**Comment by JacquesDuToit** [comment]
IF i go to website on this it connects to the device how do i set this up in your software?


https://apiv4.olarm.co/api/v4/devices?accessToken=APIKEY

________________________________
