### ISSUE TITLE
not all sites/entity loading

### ISSUE THREAD

**Issue by paulbalinnel** [rainepretorius/olarm-ha-integration#72]
### Contact Details

paul@omni-iot.co.za

### What happened?

Not all entities are loading, at best I have 2 sites loading rest shows unavailable. Am I asking too much by having 10 sites?

[home-assistant_olarm_sensors_2023-08-23T07-35-40.583Z.log](https://github.com/rainepretorius/olarm-ha-integration/files/12416523/home-assistant_olarm_sensors_2023-08-23T07-35-40.583Z.log)
<img width="323" alt="Screenshot 2023-08-23 at 09 32 55" src="https://github.com/rainepretorius/olarm-ha-integration/assets/89601096/462fdd96-6905-4698-bc2e-9b220fd40b49">
<img width="537" alt="Screenshot 2023-08-23 at 09 32 31" src="https://github.com/rainepretorius/olarm-ha-integration/assets/89601096/ea60d8ec-fd03-4620-967b-9ebf05f5f625">

### Version

2.0.1

**Comment by rainepretorius** [comment]
Hi @paulbalinnel 
I would say 10 sites are a few to many with Olarms api limiter still in place. It causes some sites to be able to update ànd other to show as unavailable. I have checked the logs and it seems that it is indeed the issue.

**Comment by rainepretorius** [comment]
The only way to support so many sites, whould be for Olarm to remove said limiter or move to a websocket api.

**Comment by paulbalinnel** [comment]
thank you for the reply, understood
