### ISSUE TITLE
[Bug]: Issue installing Integration - UI Not supported

### ISSUE THREAD

**Issue by HallCraig** [rainepretorius/olarm-ha-integration#78]
### Contact Details

craigh@tfg.co.za

### What happened?

A bug happened! When clicking your link to install integration, complains around configuration not support in the UI and I have no updates pending. Im on the latest.
![image](https://github.com/rainepretorius/olarm-ha-integration/assets/11643363/dc6e7c30-8d23-4c17-9942-7eeb3bd3f33a)

Am I doing something wrong to install this?

### Version

2.2.4

### Relevant log output form Home Assistant

```shell
see nothing in logs
```

### Downloaded integration debug logs.

```shell
see nothing in logs
```

**Comment by rainepretorius** [comment]
Try to search for Olarm Sensors.

**Comment by rainepretorius** [comment]
Have you added it via HACS, and then downloaded it with HACS before trying to install it?

**Comment by v0d0r** [comment]
+1 same issue for me.  HomeAssistant docker install.  Made sure it was on the latest version.  I have HACS installed however trying to search and download from inside HACS the "Olarm Sensors" integration does not find it. Nor does it find it if I just search for "Olarm"  See screenshot.
Trying with the link install as per @HallCraig's original post above results in the same error.  "UI Not supported"

![Screenshot 2023-10-03 at 16 10 42](https://github.com/rainepretorius/olarm-ha-integration/assets/12825145/6933bc2e-5b55-4350-b4c8-cb49cf939f12)

**Comment by rainepretorius** [comment]
You have then not added the repository to hacs as per install guide.

**Comment by rainepretorius** [comment]
> > You have then not added the repository to hacs as per install guide. Add it under the repositories tab. https://github.com/rainepretorius/olarm-ha-integration
> 
> Yep. This is my bad. I was so excited to finally see Olarm integration apparently I forgot how to read properly.  I can confirm it installed first time now no issues.  Thanks for the integration and help. ;-)

No problem. Glad you were able to install it first try with no issues. Always happy to help and support the growing comunity.

**Comment by HallCraig** [comment]
That was my problem also, a newbie mistake. I needed to add your GitHub repro as a custom repro to HACS...then I could find it and download it. My bad :) buy you a coffee shortly.
