### ISSUE TITLE
[Bug]: Unable to serialize to JSON

### ISSUE THREAD

**Issue by rwoeke** [rainepretorius/olarm-ha-integration#88]
### Contact Details

rwoeke@gmail.com

### What happened?

Hi, When Updated to the latest version of Olarm integration everything stopped working. When I try and add the integration I get this error? Am I missing something. Running version 2.2.5

Sample of error on front end
![image](https://github.com/rainepretorius/olarm-ha-integration/assets/24650121/46da6cdd-bb20-4811-a8a5-9a7fc234f9a8)

### Version

2.2.5

### Relevant log output form Home Assistant

```shell
Logger: homeassistant.components.http.view
Source: components/http/view.py:62
Integration: HTTP ([documentation](https://www.home-assistant.io/integrations/http), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+http%22))
First occurred: 17:33:03 (1 occurrences)
Last logged: 17:33:03

Unable to serialize to JSON. Bad data found at $.errors<key: <class 'str'>>=<class 'str'>(<class 'type'>
```

### Downloaded integration debug logs.

```shell
Logger: homeassistant.components.http.view
Source: components/http/view.py:62
Integration: HTTP ([documentation](https://www.home-assistant.io/integrations/http), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+http%22))
First occurred: 17:33:03 (1 occurrences)
Last logged: 17:33:03

Unable to serialize to JSON. Bad data found at $.errors<key: <class 'str'>>=<class 'str'>(<class 'type'>
```

**Comment by rainepretorius** [comment]
Hi @rwoeke ,
This seems to be an issue with Home Assistant itself as specified here: homeassistant.components.http.view in the logs. Maybe just try to redownload the integration and check again?

**Comment by rwoeke** [comment]
Only way I could get it to work is to redownload as  2.2.2
in other words happen when I upgrade olarm integration to latest

![image](https://github.com/rainepretorius/olarm-ha-integration/assets/24650121/a3a5a03c-f62e-4cda-b9a2-ee5bf4cf2b2a)

**Comment by rainepretorius** [comment]
If you download 2.2.2 and then instal 2.2.5?

**Comment by rwoeke** [comment]
not sure if thats a trick question, but I re-downloaded version 2.2.2 and installed it as well.

Running on 2.2.2 there is no issue.

![image](https://github.com/rainepretorius/olarm-ha-integration/assets/24650121/225cdd75-0c57-49db-88ce-a9f7d697d313)

**Comment by rainepretorius** [comment]
Ok. Let me look at the options one. Does it install but not later allow configuring?

**Comment by rwoeke** [comment]
I had 2.2.2 installed, updated the integration and tried to configure.
both ways does not work

**Comment by Vlerrie** [comment]
Also had issues when I upgraded to 2.2.5. Uninstalled everything and re-installed to 2.2.6 and seems to be working again.

**Comment by rwoeke** [comment]
Hello

I'm running on 2.2.6 now, but see this in the log pop up many times. Any idea what could be the cause of this. I have two devices, but only the one was selected. (Mon R) is my active one and everything seems to be working, just this error popping up in the logs.

This error originated from a custom integration.

Logger: custom_components.olarm_sensors
Source: custom_components/olarm_sensors/olarm_api.py:277
Integration: Olarm Sensors (documentation, issues)
First occurred: 07:23:58 (26 occurrences)
Last logged: 07:39:59

Olarm sensors error for device (Mon R): list index out of range
