### ISSUE TITLE
[Bug]: Installation fails - config flow

### ISSUE THREAD

**Issue by Omnimercador** [rainepretorius/olarm-ha-integration#99]
### Contact Details

Rendres [at] gmx.de

### What happened?

when i try to trigger the installation, a message indicating that the config wizard is about to starts shows for a long time. It then aborts, with the message „Config flow could not be loaded: Unknown error“

### Version

2.0.1

### Relevant log output form Home Assistant

```shell
No errors apparent
```

### Downloaded integration debug logs.

```shell
I don’t believe I get far enough to produce these?
```

**Comment by rainepretorius** [comment]
What Home Assistant version are you running?

**Comment by Omnimercador** [comment]
2024.1.2

**Comment by rainepretorius** [comment]
Can you download the most recent version from github and try again?
